import { Poppins } from "next/font/google";
import "@/styles/globals.css";
import ReduxProvider from "./ui-components/common/ReduxProvider";

// Import Poppins font
const poppins = Poppins({
  subsets: ["latin"], // Include Latin subset (or others as needed)
  weight: ["400", "500", "600", "700"], // Optional: Define specific font weights
});

export const metadata = {
  title: "TCS Virtual Assistant",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-background text-text transition-all duration-300`}
      >
        <div>{children}</div>
      </body>
    </html>
  );
}
