import { Poppins } from "next/font/google";
import "@/styles/globals.css";
import { getTheme } from "@/lib/supabase";
import Header from "./ui-components/Header";

// Import Poppins font
const poppins = Poppins({
  subsets: ["latin"], // Include Latin subset (or others as needed)
  weight: ["400", "500", "600", "700"], // Optional: Define specific font weights
});

export const metadata = {
  title: "TCS Virtual Assistant",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let themeName = "spring"; // Default theme
  try {
    const response = await getTheme();
    if (response) {
      themeName = response.data;
    }
  } catch (error) {
    console.error("Error fetching theme:", error.message);
  }

  return (
    <html lang="en" data-theme={themeName}>
      <body
        className={`${poppins.className} bg-background text-text transition-all duration-300`}
      >
        {children}
      </body>
    </html>
  );
}
